import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Command } from "commander";
import { loadIdentity } from "../identity.js";

/**
 * The installed extension, as a one-line re-export of this installation.
 *
 * `link pi` used to copy the whole built extension into
 * `~/.pi/agent/extensions/murmur.ts`. That made the copy a point-in-time
 * snapshot: upgrading murmur left the OLD extension running, with no warning
 * and nothing to compare against. The author's own machine was running an
 * extension missing two fixes that were already committed, which is exactly the
 * class of bug the extension exists to prevent -- a silently wrong state
 * report.
 *
 * A shim inverts that. The file pi loads never changes, and the code it points
 * at is whatever the current install has, so `npm install -g` is the whole
 * upgrade. The path is stable across upgrades because npm replaces a package's
 * contents in place rather than versioning the directory.
 *
 * Kept to one line on purpose: any logic here is logic that cannot be upgraded.
 */
/**
 * Identifies a generated shim, so re-linking can tell it from an older inlined
 * copy. Keyed on its own line rather than on the import statement: the shim's
 * import style already changed once (static re-export to dynamic, to fix ESM
 * hoisting), and that silently broke this check -- re-linking a shim reported
 * "replaced an inlined copy".
 */
const SHIM_MARKER = "// murmur:shim";

function shim(entry: string, storePath: string): string {
  return `${SHIM_MARKER}
// Generated by \`murmur link pi\`. Do not edit.
//
// A re-export, not a copy: the extension code lives in the murmur install, so
// upgrading murmur upgrades the extension with no reinstall step. Re-run
// \`murmur link pi\` only if the install path itself moves.
//
// The store path is set here rather than resolved by the extension. A bare
// specifier cannot resolve from ~/.pi/agent/extensions, and the failure is
// silent: the import throws, the extension swallows it, and every state report
// is dropped while the tmux badge still paints.
//
// A dynamic import, not \`export ... from\`: ESM hoists static re-exports above
// this assignment, so the extension loaded before the variable was set and read
// undefined. Verified -- the static form printed \`undefined\` in the target.
process.env.MURMUR_STORE_MODULE ??= ${JSON.stringify(storePath)};

const { default: extension } = await import(${JSON.stringify(entry)});
export default extension;
`;
}

export function registerLink(program: Command): void {
  program
    .command("link")
    .description("Install a murmur integration")
    .argument("<target>", "integration to install")
    .option(
      "--copy",
      "inline the extension instead of re-exporting it (pins to this version; needs re-linking after an upgrade)",
    )
    .action((target: string, options: { copy?: boolean }) => {
      if (target !== "pi") throw new Error(`unsupported link target: ${target}`);
      const destination = join(
        process.env.MURMUR_PI_HOME ?? homedir(),
        ".pi",
        "agent",
        "extensions",
        "murmur.ts",
      );
      mkdirSync(dirname(destination), { recursive: true });

      const entry = fileURLToPath(new URL("./extension/murmur-pi.js", import.meta.url));
      const storePath = fileURLToPath(new URL("./extension/store.js", import.meta.url));

      // Identity is `init`-generated state by design, and the extension reads
      // it with loadIdentity rather than creating one -- an agent must not
      // decide what this node is called. But the consequence is silent: with no
      // identity the extension loads, registers its handlers, and reports
      // nothing, while the tmux badge still paints. Linking is the moment to say
      // so, since it is the only time a human is looking at this path.
      const identityMissing = loadIdentity() === null;

      if (!options.copy) {
        // Say when this replaced an inlined copy. Anyone linked before the shim
        // existed has a snapshot that stopped tracking upgrades silently, and
        // "wrote a file" does not tell them their agents may have been
        // misreporting. Best effort: a missing or unreadable file is the normal
        // first-install case and says nothing.
        let replacedCopy = false;
        try {
          const existing = readFileSync(destination, "utf8");
          replacedCopy = !existing.includes(SHIM_MARKER);
        } catch {
          // No previous install.
        }
        writeFileSync(destination, shim(entry, storePath));
        console.log(destination);
        if (replacedCopy) {
          console.log(
            "Replaced an inlined copy from an older murmur. That copy was pinned to the version that wrote it, so it had stopped picking up fixes; running agents keep the old code until they restart.",
          );
        }
        if (identityMissing) {
          console.log(
            "This node has no identity yet, so the extension will record nothing. Run: murmur init",
          );
        }
        return;
      }

      // The copy path, kept for the case the shim cannot serve: an extension
      // that has to keep working when the murmur install is gone or moved.
      //
      // Pin the store import to this installation's absolute path. The
      // extension lives in ~/.pi/agent/extensions, where a bare
      // "@martintrojer/murmur/extension-store" specifier cannot resolve — not
      // even for a global install. Unpinned, every append silently no-ops:
      // the tmux badge still paints, so nothing looks broken while the log
      // stays empty and the node exports nothing.
      const source = readFileSync(entry, "utf8");
      const pinned = source.replace(
        /"@martintrojer\/murmur\/extension-store"/,
        JSON.stringify(storePath),
      );
      if (pinned === source) {
        throw new Error("link pi: could not pin the store import; extension build changed");
      }
      writeFileSync(destination, pinned);
      console.log(destination);
      if (identityMissing) {
        console.log(
          "This node has no identity yet, so the extension will record nothing. Run: murmur init",
        );
      }
    });
}
